// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories.get').default>>>>
    }
    '/api/divisions/:id/expenses/:eid': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/expenses/[eid].delete').default>>>>
    }
    '/api/divisions/:id/expenses': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/expenses/index.post').default>>>>
    }
    '/api/divisions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/index.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/index.patch').default>>>>
    }
    '/api/divisions/:id/participants/:pid': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/participants/[pid]/index.delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/participants/[pid]/index.patch').default>>>>
    }
    '/api/divisions/:id/participants': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/participants/index.post').default>>>>
    }
    '/api/divisions/:id/settlement': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id]/settlement.get').default>>>>
    }
    '/api/divisions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/index.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}